# Introduction to numpy

In [1]:
import numpy as np

## 1 DataTypes and Attributes

In [2]:
# ndarray - n' nummbers of array
a1 = np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
a1.dtype

dtype('int32')

In [5]:
type(a1)

numpy.ndarray

In [13]:
a2 = np.array([[1,2.3],[3.5,4]])
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [15]:
a2

array([[1. , 2.3],
       [3.5, 4. ]])

In [16]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [17]:
# 1 dimensional array
a1.shape

(3,)

In [18]:
# 2 dimensional array
a2.shape

(2, 2)

In [19]:
# 3 dimensional array
a3.shape

(2, 3, 3)

In [21]:
# ndmin shows the dimensional of numpy array
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [22]:
# datatype
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [23]:
# size shows total elements in array
a1.size, a2.size, a3.size

(3, 4, 18)

In [24]:
# structure type
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [26]:
# Create a datafrom from numpy array
import pandas as pd
df = pd.DataFrame(a2)

In [27]:
df

0    1
0  1.0  2.3
1  3.5  4.0

In [30]:
type(df)

pandas.core.frame.DataFrame

## 2 Creating arrays

In [31]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [32]:
sample_array.dtype

dtype('int32')

In [33]:
type(sample_array)

numpy.ndarray

In [42]:
ones = np.ones([2,3])

In [43]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
ones.dtype

dtype('float64')

In [45]:
type(ones)

numpy.ndarray

In [46]:
zeros = np.zeros([10,3])

In [47]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [56]:
random_array = np.random.randint(0,100,size = [10,10])

In [57]:
random_array

array([[53, 65, 43, 39, 35, 69, 35, 19, 99, 63],
       [30, 66, 81, 16, 77, 28, 71, 82,  5, 53],
       [37,  4, 28, 98, 62, 41, 85, 61, 67, 64],
       [61, 51, 91, 51, 18, 92, 27, 17, 81, 20],
       [71, 85, 94, 51, 53, 97, 60, 43, 38, 51],
       [96, 80, 17, 16,  9, 14, 31, 74, 33,  1],
       [34, 50, 60, 39, 20, 93, 39, 23, 48, 44],
       [ 4, 28, 33, 79, 94, 15, 84, 59, 70, 55],
       [93, 36, 23,  4, 18, 41, 28,  4, 40, 88],
       [45, 25, 27, 94, 50,  3, 35, 64,  6, 92]])

In [59]:
random_array.size

100

In [60]:
random_array.shape

(10, 10)

In [64]:
random_array_2 = np.random.random((3,3,4))
random_array_2

array([[[0.76526038, 0.69181446, 0.2090731 , 0.28723843],
        [0.42354084, 0.90868218, 0.11686948, 0.31585256],
        [0.74315605, 0.68370542, 0.27736686, 0.43420739]],

       [[0.20185118, 0.00388794, 0.58243495, 0.47945313],
        [0.49065667, 0.87263053, 0.80780434, 0.65831937],
        [0.5231268 , 0.43657101, 0.22847744, 0.49136893]],

       [[0.54076693, 0.91923042, 0.6921329 , 0.02594897],
        [0.84607048, 0.25309195, 0.83261475, 0.99615511],
        [0.09461477, 0.58730738, 0.17978556, 0.96770427]]])

In [69]:
random_array_3 = np.random.rand(5,5,5)
random_array_3

array([[[0.66733078, 0.14338431, 0.74698789, 0.05666814, 0.01653469],
        [0.10972026, 0.35937438, 0.83969245, 0.45892484, 0.56086451],
        [0.09030522, 0.22512186, 0.66069971, 0.15111365, 0.13041749],
        [0.14754905, 0.96907213, 0.90864434, 0.76422029, 0.04606399],
        [0.87924638, 0.92663965, 0.67268597, 0.06103639, 0.07669236]],

       [[0.138927  , 0.43397515, 0.98192971, 0.84411971, 0.99624355],
        [0.84417421, 0.24678522, 0.20633741, 0.36963098, 0.36290886],
        [0.10704309, 0.32250988, 0.80762946, 0.29188953, 0.12321295],
        [0.43021037, 0.18303019, 0.37262856, 0.36852347, 0.46507783],
        [0.63225521, 0.56866279, 0.2980339 , 0.25984136, 0.15969597]],

       [[0.50126011, 0.51324403, 0.40466495, 0.25831986, 0.37552966],
        [0.02717031, 0.76305379, 0.85081097, 0.23757338, 0.6126324 ],
        [0.59317333, 0.48856472, 0.0080003 , 0.82804031, 0.47175234],
        [0.5392207 , 0.25044166, 0.62957119, 0.4955405 , 0.02830023],
        [0.70913

## 3 Random seed

In [84]:
# Pseudo-random numbers

In [85]:
np.random.seed(100)
random_array_4 = np.random.randint(10, size = (5,3))
random_array_4

array([[8, 8, 3],
       [7, 7, 0],
       [4, 2, 5],
       [2, 2, 2],
       [1, 0, 8]])

In [94]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

  ## 4 Viewing array and matrices

In [96]:
random_array_4

array([[8, 8, 3],
       [7, 7, 0],
       [4, 2, 5],
       [2, 2, 2],
       [1, 0, 8]])

In [95]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 7, 8])

In [97]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2.3],
        [3.5, 4. ]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [109]:
a1, a1.shape

(array([1, 2, 3]), (3,))

In [110]:
a1[0]

1

In [111]:
a2, a2.shape

(array([[1. , 2.3],
        [3.5, 4. ]]),
 (2, 2))

In [112]:
a2[0]

array([1. , 2.3])

In [113]:
a3, a3.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
 (2, 3, 3))

In [114]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [128]:
a3[:2,:2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [130]:
a3[:1,:2,1]

array([[2, 5]])

In [132]:
a4 = np.random.randint(10,size=(2,3,4,5))

In [136]:
a4.dtype, a4.shape, a4.ndim

(dtype('int32'), (2, 3, 4, 5), 4)

In [137]:
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [153]:
a4[:1, :2, :3, :1]

array([[[[3],
         [5],
         [9]],

        [[1],
         [7],
         [7]]]])

In [154]:
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [160]:
a4[0,2,0]

array([4, 3, 1, 9, 5])

In [162]:
a4[:,:,:,:4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])